sudo: required
services:
- docker
before_install:
- docker build -t dimitriosd/cicd-fibapp-ui-test -f ./cicd-fibapp-ui/Dockerfile.dev ./cicd-fibapp-ui
script:
- docker run -e CI=true dimitriosd/cicd-fibapp-ui-test npm test -- --coverage
after_success:
- docker build -t dimitriosd/cicd-fibapp/client ./cicd-fibapp-ui
- docker build -t dimitriosd/cicd-fibapp/nginx ./nginx
- docker build -t dimitriosd/cicd-fibapp/api ./cicd-fibapp-server
- docker build -t dimitriosd/cicd-fibapp/worker ./cicd-fibapp-redis
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push dimitriosd/cicd-fibapp/client
- docker push dimitriosd/cicd-fibapp/nginx
- docker push dimitriosd/cicd-fibapp/api
- docker push dimitriosd/cicd-fibapp/worker
