sudo: required
services:
- docker
before_install:
- docker build -t dimitriosd/cicd-fibapp-ui-test -f ./cicd-fibapp-ui/Dockerfile.dev ./cicd-fibapp-ui
script:
- docker run -e CI=true dimitriosd/cicd-fibapp-ui-test npm test -- --coverage
after_success:
- docker build -t dimitriosd/multi-client ./cicd-fibapp-ui
- docker build -t dimitriosd/multi-nginx ./nginx
- docker build -t dimitriosd/multi-apiapi ./cicd-fibapp-server
- docker build -t dimitriosd/multi-worker ./cicd-fibapp-redis
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push dimitriosd/multi-client
- docker push dimitriosd/multi-nginx
- docker push dimitriosd/multi-api
- docker push dimitriosd/multi-worker
