sudo: required
services:
- docker
before_install:
- docker build -t dimitriosd/cicd-fibapp-ui -f ./cicd-fibapp-ui/Dockerfile.dev ./cicd-fibapp-ui
script:
- docker run -e CI=true dimitriosd/cicd-fibapp-ui npm test -- --coverage
after_success:
- docker build -t registry.heroku.com/cicd-fibapp/client ./cicd-fibapp-ui
- docker build -t registry.heroku.com/cicd-fibapp/nginx ./nginx
- docker build -t registry.heroku.com/cicd-fibapp/api ./cicd-fibapp-server
- docker build -t registry.heroku.com/cicd-fibapp/worker ./cicd-fibapp-redis
- echo "$HEROKU_AUTH_TOKEN" | docker login -u "_" --password-stdin registry.heroku.com
- docker push registry.heroku.com/cicd-fibapp/client
- docker push registry.heroku.com/cicd-fibapp/nginx
- docker push registry.heroku.com/cicd-fibapp/api
- docker push registry.heroku.com/cicd-fibapp/worker
- (echo "$HEROKU_EMAIL" echo "$HEROKU_PASSWORD") | heroku login
- heroku container:release client nginx api worker --app cicd-fibapp
deploy:
  provider: script
  api_key:
    secure: jrP/ydOkdsGjYw3K4A2yJAU32j9+kQNLEeU1jYvfREyQM4EC6wHiYbNEo7RpUX0BC87xjJUUALtmsXvPgcS5ykRzssGgcVqts5Hk0Vl0Qsec+oo8GgV25ULBaDU+6rM8D5089gba7vpr9TSDXlQqi+A4ebdtEty+8s5J7kK9UwDwCu6YQmjQnsbZBjibdSEInpQp0exWJK3dluBbLNggvnIWI3lOsuIUkV6v129f6qlchjIOV+jMwNy7HbRmfVVytPmTVtcDahXO2wKJHtSh5oR4X+s/Qy3+js0b21XWkDv/9hVU+bP/o+LgkaUsKvc0Ve2HKKj3qO0gckJB0INRKiM2svgr6OQL/8r9n3jAFiitXl1KhuTnzG46Lpii58mZqB0c7tE9JLB3gJbLBJYVJZAAG0rgtdpHGSV+JUZqs6ChTowgbnyOY9aBQ1zMtRVrpamode0urDbFuNY1Na48Lp3avkjySSHq1r9aE/1DqltPt00rdLhSZljZMz/uCVGliD0iCKJTcCoKa3jL30k5/3DJcO2LhRr8HWZBMfeIZbfzhbdMh38uNuYywCd9br5GIfmaFKQ7xdJcaIwMmrTKz7X77JWIKvTOJ1LvBeQDYNO1AigNTC63ZpcyhFayAbAE6ui8l3v8MJhhlwDwgFPxlWFJ8E/flkQC8CJTM2S7xlk=
  script: heroku container:release client nginx api worker --app cicd-fibapp;
